vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pe", vim.cmd.Ex)
vim.keymap.set("n", "<leader>t", vim.cmd.tabnew)
vim.keymap.set("n", "<C-h>", vim.cmd.tabprevious)
vim.keymap.set("n", "<C-l>", vim.cmd.tabnext)
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("v", "<C-c>", "<Esc>")
vim.keymap.set("n", "<C-x>", function()
    vim.cmd("split")
    vim.cmd("wincmd j")
    vim.cmd("terminal")
end)
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
